# Generated by Django 3.2.23 on 2024-05-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.CharField(max_length=10)),
                ('c_time', models.CharField(max_length=10)),
                ('button_pressed', models.IntegerField()),
                ('total_predictions', models.IntegerField()),
                ('correct_predictions', models.IntegerField()),
                ('incorrect_predictions', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
